### ISSUE TITLE
Error Message creatin kernel parameters fs.aio-max-nr and fs.file-max

### ISSUE THREAD

**Issue by termanico** [MicrosoftDocs/CommandLine-Docs#100]
Hi,
while trying to install SAP HANA Express on WSL (i know, it's not officially supported by SAP - but would be a nice alterntive to a VM installation in terms of memory consumption and performance ;-), I get an error message creating fs kernel parameters aio-max-nr and fs.file-max (parameter not found). I tried to insert it with sysctl -p /etc/sysctl.conf - but just got an message, saying the corresponding directory entries were not found!?
Any hints on this? Is it not implemented yet? does it com with an insider build? I am on build 15063.
The entries in /etc/sysctl.conf are:
fs.file-max=20000000
fs.aio-max-nr=1196608
regards and thx in advance for any infos - it's more than welcomed :-)
Thorsten

**Comment by bitcrazed** [comment]
Hi @termanico, thanks for your feedback. Note that we're working with SAP on getting HANA running on WSL. We'll make any announcements on [our blog](https://blogs.msdn.microsoft.com/commandline) when we make progress.

Also, please note that this repo's issue tracker is specifically for doc issues - issues with WSL itself can be posted to https://github.com/microsoft/bashonwindows
