### ISSUE TITLE
Environment Variables not passed to Win32 processes

### ISSUE THREAD

**Issue by johndaintree** [MicrosoftDocs/CommandLine-Docs#102]
( I hope it's OK to report issues this way).

In order to replace Cygwin/MKS toolkit as a build environment on Windows it's important to be able to run the VS compiler from a bash shell/script. However, it looks like environment variables are not passed to child processes:

```
johnd@Johnd-PC:/mnt/e/tmp$ export INCLUDE=.
johnd@Johnd-PC:/mnt/e/tmp$ cl.exe -c ./jd.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

jd.c
./jd.c(1): fatal error C1034: jd.h: no include path set
```

Also,

```
johnd@Johnd-PC:~$ export JUNK=JD_JUNK
johnd@Johnd-PC:~$ notepad
```

If I then examine the notepad process with sysinternals' "Process Explorerer" I can see that JUNK is not in its environment.

**Comment by sunilmut** [comment]
@johndaintree - Thanks for your post. Can you please post this feedback [here](https://github.com/Microsoft/BashOnWindows/issues), following the [template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md). This repo is for documentation. Issues are tracked in the other repo.

**Comment by johndaintree** [comment]
Yes of course. Obvious now I've read the url for this repository.  I've done that.

**Comment by sunilmut** [comment]
Thanks. Closing this out.
