### ISSUE TITLE
loop device is not present

### ISSUE THREAD

**Issue by xuqihang** [MicrosoftDocs/CommandLine-Docs#116]
Hoping to have it implemented so that I can mount a floppy image and read & write files.
Or it's an abnormal installation?

**Comment by sunilmut** [comment]
@xuqihang - Thanks for your post. This repo is only for documentation. All issues are being tracked in [this](https://github.com/Microsoft/BashOnWindows/issues) repo. Please (re)post your issue there, after following the [template](https://github.com/Microsoft/BashOnWindows/blob/master/ISSUE_TEMPLATE.md).
