### ISSUE TITLE
Ping works, but no traceroute

### ISSUE THREAD

**Issue by elmorekevin** [MicrosoftDocs/CommandLine-Docs#125]
I know some of the network tools had been lagging in implementation from the start, but ping and nslookup work fine on my machine. It's just traceroute that doesn't work yet. I saw a note in Build 16176 "Added IP(V6)_MTU socket option for apps node, traceroute, dig, nslookup, host" and I'm on Build 16251.  What does this line mean?

Does IPv4 traceroute still just not work yet in general, or is it my machine, or something else?

We are an internet provider and traceroute is a pretty crucial tool. I'd love to not have to go back to Command Prompt for just this command.

Thanks,
Kevin

**Comment by sunilmut** [comment]
@elamalani - Thanks for your post. This repo is for documentation. The repo to post issues is [this](https://github.com/Microsoft/BashOnWindows/issues). I will close this issue out, please feel free to post it in the other repo.

As for `traceroute`, it currently does not work for either IPv4/v6. Basically, it requires support for `AF_PACKET` socket address family, which is missing (both natively in Windows and consequently in WSL). If you would like to see support for it, help us prioritize by casting your vote for [this](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) ticket in our user voice page.

**Comment by elmorekevin** [comment]
Thanks for the response. I guess the traceroute that works from basic Command Prompt does not require AF_PACKET. I just voted for the other issue.

**Comment by sunilmut** [comment]
@eamonoreilly - Actually, you are right. I just looked at a strace of `tracepath` and it doesn't has a dependency on `AF_PACKET`. It is `nmap` that requires `AF_PACKET`. Sorry about the confusion. Your vote is still good though :).
