### ISSUE TITLE
Non-ASCII characters problems

### ISSUE THREAD

**Issue by cowens** [MicrosoftDocs/CommandLine-Docs#13]
I copied over my .vimrc from a working Ubuntu machine.  One of the lines is

```
set listchars=tab:⇥·,eol:↵,trail:·
```

This was mangled to

```
set listchars=tab:�~G���,eol:�~F�,trail:��
```

and it caused vim to output the following message:

```
Error detected while processing /home/cowens/.vimrc:
line   88:
E474: Invalid argument: listchars=tab:�~G���,eol:�~F�,trail:��
```

I then attempted to copy and paste UTF-8 data and all UTf-8 characters were stripped from the paste.  As a further test, I wrote a simple Perl 5 script to output an e acute and got the following output

```
$ perl -CSDL -E 'say "\x{e9}"'
�
```

Next I tried setting the encoding to CP1252, and still didn't get an e acute:

```
$ perl -E 'binmode STDOUT, ":encoding(cp1252)"; say "\x{e9}"'
�
```

A test of the output shows that a Latin1/CP1252 e acute is being written:

```
$ perl -E 'binmode STDOUT, ":encoding(cp1252)"; say "\x{e9}"' | perl -Mbytes -nlE 'for my $c (split //) { printf "0x%02x $c\n", ord $c }'
0xe9 �
```

**Comment by bitcrazed** [comment]
This is, alas, a limitation of the current Windows Console which cannot (currently) perform font-fallback, allowing it to select different fonts for different UNICODE code-points.

We are working to solve this issue in future versions of Windows.

Also, please note that this repo's issue tracker is specifically for doc issues - issues with the Console itself can be posted to https://github.com/microsoft/Console
