### ISSUE TITLE
No network

### ISSUE THREAD

**Issue by jwwisgerhof** [MicrosoftDocs/CommandLine-Docs#14]
Bash starts up correctly, and all standard programs work as you would expect. The network seems to not be initialized at all though. Tried running as admin, restarted, etc:

nslookup:
`root@localhost:/# nslookup google.com

socket.c:2447: setsockopt(20, SO_TIMESTAMP) failed: Invalid argument

socket.c:1915: internal_send: 127.0.0.1#53: Invalid argument

socket.c:2447: setsockopt(21, SO_TIMESTAMP) failed: Invalid argument

socket.c:2476: setsockopt(21, IPV6_RECVPKTINFO) failed: Invalid argument

;; connection timed out; no servers could be reached`

Happy to provide more information if requested. I saw a few other people having similar issues, but no issue logged yet.

Additional information:
- No VPN
- No Proxy
- One network adapter (wired)
- Internet works of course in Windows applications

**Comment by kterhorst** [comment]
I solved this problem by specifying a DNS server in /etc/resolv.conf:

```
root@localhost:/mnt# cat /etc/resolv.conf
nameserver 8.8.8.8
```

**Comment by jwwisgerhof** [comment]
Beautiful that works. Thanks @kterhorst. Should probably still be logged as an issue though.

**Comment by chaosjester** [comment]
I have that issue and adding the nameserver to /etc/resolv.conf did not resolve it

**Comment by throx** [comment]
Yep - nslookup failing:

`root@localhost:/etc# cd
root@localhost:~# nslookup microsoft.com
socket.c:2447: setsockopt(20, SO_TIMESTAMP) failed: Invalid argument
socket.c:1915: internal_send: 192.168.0.1#53: Invalid argument
socket.c:2447: setsockopt(21, SO_TIMESTAMP) failed: Invalid argument
socket.c:2476: setsockopt(21, IPV6_RECVPKTINFO) failed: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::1#53: Invalid argument
socket.c:2447: setsockopt(22, SO_TIMESTAMP) failed: Invalid argument
socket.c:2476: setsockopt(22, IPV6_RECVPKTINFO) failed: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::2#53: Invalid argument
socket.c:1915: internal_send: 192.168.0.1#53: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::1#53: Invalid argument
socket.c:1915: internal_send: fec0:0:0:ffff::2#53: Invalid argument
^C`

**Comment by cowens** [comment]
The syscalls that are failing are:

```
capget({_LINUX_CAPABILITY_VERSION_3, 0}, NULL) = -1 EFAULT (Bad address)
```

and

```
socket(PF_INET, SOCK_RAW, IPPROTO_ICMP) = -1 ESOCKTNOSUPPORT (Socket type not supported)
```

The first should not be happening (ie it is a bug in WSL).  The docs say:

```
EFAULT Bad memory address.  hdrp must not be NULL.  datap may be NULL only when the user is trying to determine the preferred capability version format supported by the kernel.
```

HDRP is not null (it is `{_LINUX_CAPABILITY_VERSION_3, 0}`) and the call is trying to determine the preferred capability version format, so it should be (and is) NULL.

The second may be related to the earlier failure or Windows doesn't support raw sockets for ICMP, I am not sure.

**Comment by yuanfangtardis** [comment]
my bash did not network either . It seems my wireless adapter is not detected . 'ifconfig" command shws messages like this: Warning: "cannot open /proc/net/dev (No Such file or directory). Limited output "  .
     How can I fix it?

**Comment by ophiry** [comment]
I had similar problem - it appears the issue is that IP6 addresses have precedence over IP4
a solution is described in: http://askubuntu.com/questions/32298/prefer-a-ipv4-dns-lookups-before-aaaaipv6-lookups/38468#38468

**Comment by bitcrazed** [comment]
Thanks for all your reports. We have two key issues with networking at the moment:
1. We don't yet support ICMP (affecting Ping)
2. We have an IPv6 related issue affecting our configuration of resolv.conf and thus DNS issues.

Bear with us while we work on fixes for future builds.

**Comment by bitcrazed** [comment]
Thanks for reporting this issue - it was fixed back in Anniversary Update.
