### ISSUE TITLE
Cannot start sshd server

### ISSUE THREAD

**Issue by vivimice** [MicrosoftDocs/CommandLine-Docs#17]
`~# apt-get install ssh`
`~# /etc/init.d/ssh start`
`* /dev/null is not a character device!`

And I cannot remove /dev/null and re-create with `mknod`

**Comment by MakiseKurisu** [comment]
As a workaround, you can use dropbear for ssh.

apt-get install dropbear
dropbear -F -p 2222

This will open ssh server at port 2222. -F option will keep dropbear running at foreground, otherwise it will be killed.

**Comment by vivimice** [comment]
`root@localhost:~# ssh localhost -p 2222`
`root@localhost's password:`
`PTY allocation request failed on channel 0`
`shell request failed on channel 0`

Seems step into that landmine:
http://blog.dustinkirkland.com/2016/03/ubuntu-on-windows.html

> Is everything working exactly as expected?  No, not quite.  Not yet, at least.  The vast majority of the LTP passes and works well.  But there are some imperfections still, especially around tty's an the vt100.  My beloved byobu, screen, and tmux don't quite work yet, but they're getting close!

**Comment by bitcrazed** [comment]
Please note that openSSH now works as expected on WSL in Creators Update and later.

Also, please note that this repo's issue tracker is specifically for doc issues - issues with WSL itself can be posted to https://github.com/microsoft/bashonwindows
