### ISSUE TITLE
Unable to pipe Bash output to other programs

### ISSUE THREAD

**Issue by raeesbhatti** [MicrosoftDocs/CommandLine-Docs#8]
I'm unable to spawn Bash from NodeJS. If you try to, it will return this error: `Error: 0x80070057`
### How to reproduce:
- Install NodeJS
- Run `node` in CMD
- Type: 

```
cp = require('child_process');
proc = cp.spawnSync('cmd', ['/c', 'bash -c "ls"'], {encoding: 'utf8'}).output
```

It outputs:

```
[ null, 'Error: 0x80070057\r\r\n', '' ]
```

**Comment by justinhixson** [comment]
This is actually a pretty interesting one.  in Python, for example, I can spawn bash just fine with the `subprocess` module, but only under certain circumstances.  consider the following script:

    import subprocess
    subprocess.run(["bash","-c","ls"])

this is saved as bash.py

`c:\>python bash.py`    works
    c:\>python
    >>import subprocess;
    >>subprocess.run(["bash","-c","ls"])

also works

however, I found it very interesting that `C:\>echo import subprocess; subprocess.run(["bash","-c","ls"]); | python`  does NOT work,  (note that something like `C:\Users\Justin>echo import subprocess; subprocess.run(["notepad"]); | python` does indeed work.

**Comment by raeesiqbal** [comment]
Can confirm. This is a problem with bash having problems with output piping. If I specify `{ stdio: 'inhert' }`, it works but that way I then have no way of getting that data. `{ stdio: 'pipe' }` produces the error above

**Comment by MadcowD** [comment]
I've made a related issue in Bash on Windows. [#312](https://github.com/Microsoft/BashOnWindows/issues/312)

**Comment by bitcrazed** [comment]
Thanks for the issue report - this was fixed in Creators Update.

**Comment by justinhixson** [comment]
Thank you so much for this! This has been my most anticipated feature for the Linux Subsystem since i first hear about it!  I am enjoying it immensely, and can confirm that it now works exactly as one would imagine it would.  Thanks again!!!!!
