### ISSUE TITLE
missing norwegian keymap and no way to set it with localectl.

### ISSUE THREAD

**Issue by brumle80** [MicrosoftDocs/CommandLine-Docs#9]
error when running localectl:

Failed to get D-Bus connection: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

also no way atm to type @ unless it's a special keycombo?

**Comment by bitcrazed** [comment]
Thanks for the report. We're taking a look at this.

**Comment by warpdesign** [comment]
Similar problem with French keyboard layout: there's no way to make characters that need alt-gr combination for exemple. Same thing for accents which doesn't work.

**Comment by SonGokussj4** [comment]
The same problem with Czech keyboard. In BASH console.
when pressing: [ALTGR] + [,] / [.] / [;], that sould get me [<] / [>] / [$] but nothing.

When trying in CMD, everything works.

When trying in cmder / conemu, everything works. But there is another problem. Arrow keys won't work.

**Comment by misenesi** [comment]
See [https://github.com/Microsoft/BashOnWindows/issues/11](url) for more details.

**Comment by bitcrazed** [comment]
Hi all. Thanks for discussing this issue, but note that this repo's issue tracker is just for doc issues. Please report/discuss WSL issues in our main repo here: https://github.com/Microsoft/BashOnWindows
